name: NPM Publish and GitHub Release
on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "18"
          registry-url: 'https://registry.npmjs.org'

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install dependencies browser-sdk
        run: cd browser-sdk && pnpm install

      - name: Build browser-sdk
        run: cd browser-sdk && pnpm run prepare

      - name: Copy WASM files for browser-sdk
        run: |
          mkdir -p browser-sdk/dist/wasm
          cp -r browser-sdk/src/wasm/* browser-sdk/dist/wasm/

      - name: Publish browser-sdk to NPM
        uses: JS-DevTools/npm-publish@v3
        with:
          token: ${{ secrets.NPM_CLIENT_SDK_TOKEN }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_CLIENT_SDK_TOKEN }}
        run: cd browser-sdk && npm publish

      - name: GitHub Release
        uses: softprops/action-gh-release@v2
